### ISSUE TITLE
JsonWriter can not be resolved to a type

### ISSUE THREAD

**Issue by ywnotts** [GreenDelta/olca-modules#1]
the json-simple-1.1 can not be copied into libs by 'maven package' command, as a result, a error is indicated by Eclipse as that 'JsonWriter can not be resolved to a type'. i have tried to add the jar through JavaPath, but it is failure. is it a existing issue? or there is something wrong with my methods to deploy? thanks.

**Comment by msrocka** [comment]
Thank you for posting the first issue here!

There shouldn't be a dependency to the json-simple API anymore. You may have to also update the olca-app project to the current version (it contains the references to the olca-jsonld API which contains the JsonWriter in the pom.xml and MANIFEST.MF). Does this solve this issue?

(Note that the jsonld API is still in development and the names may change; e.g. I just renamed the JsonWriter to JsonExport to make it more consistent with the other import/export classes in the io package).

**Comment by ywnotts** [comment]
hi Michael, thanks for your response. 

I solved the problem by changing this syntax as 'import org.openlca.jsonld.output.JsonWriter', and i'm sure the version of olca-app project i'm using is the latest.

Hope my solutions are helpful for your further work.

**Comment by msrocka** [comment]
Ah ok, great!
