### ISSUE TITLE
Compile error in org.openlca.ilcd.commons.Refs.java

### ISSUE THREAD

**Issue by littlebunch** [GreenDelta/olca-modules#10]
[ERROR] /Users/gary.moore/git/olca-modules/olca-ilcd/src/main/java/org/openlca/ilcd/commons/Ref.java:[114,21] type org.openlca.ilcd.commons.Class does not take parameters

Fixed by adding java.lang.Class<? extends IDataSet> getDataSetClass() to method signature.

This using java 1.8.0_111 on MacOs.

**Comment by msrocka** [comment]
Maybe something went wrong when merging different branches because the class `org.openlca.ilcd.commons.Class` was renamed to `org.openlca.ilcd.commons.Category` on [3 Nov 2016](https://github.com/GreenDelta/olca-modules/commit/1d93bfbc8e3d36217a7d677360c8742904bdd93b)
