### ISSUE TITLE
OLCA-Geo Maven links out of date 

### ISSUE THREAD

**Issue by tur-ium** [GreenDelta/olca-modules#20]
Hi there,

Having some trouble with Maven not finding the following artifacts when running `mvn install`

`org.geotools:gt-shapefile:jar:10.3, org.geotools:gt-opengis:jar:10.3, org.geotools:gt-api:jar:10.3, org.geotools:gt-main:jar:10.3, org.geotools.xsd:gt-xsd-kml:jar:10.3, org.geotools.xsd:gt-xsd-core:jar:10.3: Could not find artifact org.geotools:gt-shapefile:jar:10.3 in osgeo (**http://download.osgeo.org/webdav/geotools/**) 
`
Does the url in bold need updating perhaps?

**Comment by hphungnal** [comment]
I ran into the same issue. It looks like the geotools repository was recently migrated.

Please see: https://www.osgeo.org/foundation-news/new-osgeo-repo/

I updated my pom.xml in olca-geo to match the example here: http://geotoolsnews.blogspot.com/2020/04/change-to-maven-repositories.html

**Comment by msrocka** [comment]
Thanks @hphungnal . Note that GeoTools was removed from the dependencies in the current dev branch (`j14`) as it is not required anymore. This will be moved into the master very soon.
