### ISSUE TITLE
Publish Jar to a maven repository

### ISSUE THREAD

**Issue by AlbanSeurat** [GreenDelta/olca-modules#28]
Would it be possible to have your jar published in a maven repository (maven central or another) ?

**Comment by msrocka** [comment]
Yes this is true and we are working in that. I will comment on this issue when there is some progress. We have `org.openlca` now registered as a group and started to push some dependencies to Maven Central:
https://search.maven.org/search?q=org.openlca. 

We are working on the backend for openLCA 2 in the current `master` branch. The version in that branch is 2.0.0 but should be
`2.0.0-SNAPSHOT`. The `1.11` branch is the current backend of the openLCA 1.11 version. We will try to push the 1.11 version to the Maven central (but this works with Java 8 only). When the 2.0 version is a bit more stable, we will publish this there too and from there on we will follow a more Maven friendly workflow...

**Comment by AlbanSeurat** [comment]
Thanks for your feedback!
I am actually interested in orca-modules 1.8.0 (git tag v1.8.0) for now, so if you publish first this one, it is fine for me.

**Comment by msrocka** [comment]
The v1.11.0 modules are now available on Maven Central: https://search.maven.org/search?q=openlca

**Comment by AlbanSeurat** [comment]
I do not see olca-simapro-csv in master branch. Do you plan to remove the support of simapro CSV in openlca 2.0 ?

**Comment by msrocka** [comment]
It is now in a separate project: https://github.com/GreenDelta/olca-simapro-csv and published in the Maven Central Repo
