### ISSUE TITLE
How to binds flows descriptor to tech matrix

### ISSUE THREAD

**Issue by NicolasDumoulin** [GreenDelta/olca-modules#3]
Hi,

I'm trying to hack the LcaCalculator class for performing new analysis, but I'm stucked on retrieving the flows and processes names. I would like to describe the elements of the technology matrix with the associated flows and processes.
What I don't understand is that in my example (glass wool mat at plant from ecoivent 2.1), I have the following dimensions:
- technology matrix inventoryMatrix.getTechnologyMatrix() 1956x1956
- flows list inventoryMatrix.getFlowIndex().getFlowIds() = 1340
  So, I'm wrong :-)
  But how can I get the corresponding flow and process of an element of the technology matrix?
  Thanks

**Comment by msrocka** [comment]
The names are maybe a bit confusing: in the inventory matrix the `flowIndex` contains the mapping of flow IDs to the rows in the intervention matrix and the `productIndex` the mappings of the process products to the rows and columns of the technology matrix (and the columns of the intervention matrix). 

In the product index the process products are identified by a pair of process ID and product flow ID (as a process can have multiple output products and the same product can be provided by different processes). The package `org.openlca.core.results` contains some wrapper classes (e.g. the class ContributionResultProvider) with which you can get the additional information like flow names etc. in an easy way.
