### ISSUE TITLE
How to connect to collaboration server? 

### ISSUE THREAD

**Issue by SamiraHuber** [GreenDelta/olca-modules#33]
Hello, could someone please help me by connecting to collaboration server on a linux machine without a gui? cannot find the "cloud" module... 
Best Regards and thanks in advance!

**Comment by SamiraHuber** [comment]
Oh I noticed that you added olca-git for olca-cloud. Is there any documentation on how to import a database?

**Comment by msrocka** [comment]
This is currently under development and not documented yet. We are moving to use plain Git repositories for data exchange. For connecting to a current version of the collaboration server see the `olca-cloud` module in the `1.11` branch.

An example for writing to a Git repo can be found here: https://github.com/GreenDelta/olca-modules/blob/master/olca-git/src/test/java/org/openlca/git/WriteReadTest.java

To see how the import and export via Git works, you can have a look how it is done in the app, e.g. check where [GitStore](https://github.com/GreenDelta/olca-app/blob/master/olca-app/src/org/openlca/app/collaboration/ui/io/GitStore.java) is used which is an implementation of the JSON reader / writer interface, e.g. here: https://github.com/GreenDelta/olca-app/blob/master/olca-app/src/org/openlca/app/collaboration/ui/navigation/actions/MergeAction.java#L69

But as said, this is all heavily under development and the API will change for sure. More functions like the GitStore will go into this repo once the API is more stable.
